server:
  port: 8030

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/letter
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 5MB
      max-file-size: 20MB
      location:
jwt:
  config:
    key: letter

custom:
  config:
    ignores:
      post:
        - "/login"
        - "/register"
      get:
        - "/file/*"

#apollo
app:
  id: letter

apollo:
  meta: http://localhost:8080
  access-key:
    secret: 0582299fcfd244f0bc24a2321addc872